```yaml
name: Ultimate CI for Python, C, and D with Ollama

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual runs for debugging

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        include:
          - python-version: '3.12'
            dlang-version: '2.108.0'  # Latest stable D version
            build-type: 'Release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for commit analysis

    - name: Cache dependencies
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.cache/pip
          ~/.ccache
          ~/.dub
          build/
        key: ${{ runner.os }}-deps-${{ matrix.python-version }}-${{ matrix.dlang-version }}-${{ matrix.build-type }}-${{ hashFiles('requirements.txt', 'Makefile', '*.d', 'CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-deps-${{ matrix.python-version }}-${{ matrix.dlang-version }}-${{ matrix.build-type }}-
        enableCrossOsArchive: false
        fail-on-cache-miss: false
        save-always: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up D language
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd
        version: ${{ matrix.dlang-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ libcurl4-openssl-dev libssl-dev libwebsockets-dev ccache clang-tidy clang-format python3-dev build-essential cmake

    - name: Setup Flowpipe
      uses: turbot/flowpipe-action-setup@v1.0.0
      with:
        flowpipe-version: latest

    - name: Handle D files to prevent Makefile conflicts
      run: |
        mkdir -p d_files
        find . -name "*.d" -not -path "./d_files/*" -exec mv {} d_files/ \;
        echo "Moved .d files to d_files/ to avoid Makefile conflicts"

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt numpy pandas matplotlib ollama || echo "Warning: Failed to install some dependencies. Continuing."
        else
          echo "Warning: requirements.txt not found. Skipping Python dependency installation."
        fi
      continue-on-error: true

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve &
        sleep 5  # Wait for Ollama server to start
        ollama pull llama3.1  # Pull a lightweight model
      continue-on-error: true

    - name: Validate Ollama integration
      run: |
        source venv/bin/activate
        if [ -f ollama_client.py ]; then
          python ollama_client.py --test
          echo "Ollama integration validated successfully."
        elif [ -f llm_client.py ]; then
          python llm_client.py --test --use-ollama
          echo "Ollama integration validated via llm_client.py with Ollama backend."
        else
          echo "Warning: No Ollama client script found. Skipping Ollama validation."
        fi
      continue-on-error: true

    - name: Run C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2.14.0
      with:
        style: llvm
        extensions: c,h,cpp,hpp
        tidy-checks: 'boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*'
        version: 14
        verbosity: info
        files-changed-only: true
        ignore: .github|d_files
        thread-comments: true
        no-lgtm: true
        step-summary: true
        file-annotations: true
        jobs: 0  # Use all CPU cores

    - name: Build D code
      run: |
        if ls d_files/*.d >/dev/null 2>&1; then
          dub build --root d_files --compiler=dmd
        else
          echo "No .d files found. Skipping D build."
        fi
      continue-on-error: true

    - name: Configure CMake
      id: configure_cmake
      run: |
        if [ -f CMakeLists.txt ]; then
          cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -S .
          echo "CMake configured successfully."
        else
          echo "Warning: CMakeLists.txt not found. Falling back to Makefile or direct compilation."
          echo "CMAKE_FOUND=false" >> $GITHUB_ENV
        fi
      continue-on-error: true

    - name: Build C code with CMake
      if: steps.configure_cmake.outcome == 'success' && env.CMAKE_FOUND != 'false'
      id: build_c_code_cmake
      run: |
        cmake --build build --parallel $(nproc) > build.log 2>&1
      continue-on-error: true

    - name: Build C code with Makefile or fallback
      if: steps.configure_cmake.outcome != 'success' || env.CMAKE_FOUND == 'false'
      id: build_c_code_fallback
      run: |
        export CC="ccache gcc"
        if [ -f Makefile ]; then
          make -j$(nproc) > build.log 2>&1
        else
          echo "Makefile not found. Compiling C files directly."
          gcc -o program *.c -I. -lcurl -lssl -lcrypto -lwebsockets -lpython3.12 > build.log 2>&1
        fi
      continue-on-error: true

    - name: Retry building C code if failed
      if: steps.build_c_code_cmake.outcome == 'failure' || steps.build_c_code_fallback.outcome == 'failure'
      run: |
        export CC="ccache gcc"
        if [ -f CMakeLists.txt ]; then
          cmake --build build --parallel $(nproc) --clean-first > build.log 2>&1
        elif [ -f Makefile ]; then
          make clean && make -j$(nproc) > build.log 2>&1
        else
          gcc -o program *.c -I. -lcurl -lssl -lcrypto -lwebsockets -lpython3.12 > build.log 2>&1
        fi
      continue-on-error: true

    - name: Upload build logs
      if: steps.build_c_code_cmake.outcome == 'failure' || steps.build_c_code_fallback.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build.log
        retention-days: 7

    - name: Run comprehensive Python tests
      run: |
        source venv/bin/activate
        if [ -f comprehensive-test.py ]; then
          python comprehensive-test.py
        elif [ -f quantum_drug_simulator.py ]; then
          python quantum_drug_simulator.py --test --use-ollama
        elif [ -f test-execution.py ]; then
          python test-execution.py --use-ollama
        else
          echo "Warning: No test scripts found. Skipping comprehensive tests."
        fi
      continue-on-error: true

    - name: Run unit tests with pytest
      uses: fylein/python-pytest-github-action@v2
      with:
        pytest-args: --cov=./ --cov-report=xml --cov-report=html
      continue-on-error: true

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
        retention-days: 7

    - name: Validate BioCube simulation with Ollama
      run: |
        source venv/bin/activate
        if [ -f biocube.py ]; then
          python biocube.py --simulate --use-ollama --output biocube_results.json
          echo "BioCube simulation completed with Ollama. Results saved to biocube_results.json."
        else
          echo "Warning: biocube.py not found. Skipping BioCube simulation."
        fi
      continue-on-error: true

    - name: Upload BioCube results
      if: exists('biocube_results.json')
      uses: actions/upload-artifact@v4
      with:
        name: biocube-results
        path: biocube_results.json
        retention-days: 7

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const issue = await github.rest.issues.create({
            owner,
            repo,
            title: 'CI Workflow Failure',
            body: 'The CI workflow failed. Check logs, build artifacts, linter reports, Ollama validation, and BioCube results (if applicable).\n\nRun ID: ${{ github.run_id }}\nCommit: ${{ github.sha }}',
          });
          console.log(`Issue created: ${issue.data.html_url}`);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate dependency report
      run: |
        source venv/bin/activate
        pip list > pip-requirements-report.txt
        dpkg -l | grep -E 'gcc|g++|libcurl|libssl|libwebsockets|ccache|clang-tidy|clang-format|python3-dev|build-essential|cmake' > system-requirements-report.txt
      continue-on-error: true

    - name: Upload dependency reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-reports
        path: |
          pip-requirements-report.txt
          system-requirements-report.txt
        retention-days: 7
```
